#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v27
# autospec commit: 65cf152
#
Name     : perl-Mail-Sendmail
Version  : 0.82
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Mail-Sendmail-0.82.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Mail-Sendmail-0.82.tar.gz
Summary  : 'Simple platform independent mailer'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Mail-Sendmail-perl = %{version}-%{release}
Requires: perl(MIME::QuotedPrint)
BuildRequires : buildreq-cpan
BuildRequires : perl(Sys::Hostname::Long)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Perl 5 module Mail::Sendmail
Mail::Sendmail is a pure perl module that provides a simple
platform-independent mailer.

%package dev
Summary: dev components for the perl-Mail-Sendmail package.
Group: Development
Provides: perl-Mail-Sendmail-devel = %{version}-%{release}
Requires: perl-Mail-Sendmail = %{version}-%{release}

%description dev
dev components for the perl-Mail-Sendmail package.


%package perl
Summary: perl components for the perl-Mail-Sendmail package.
Group: Default
Requires: perl-Mail-Sendmail = %{version}-%{release}

%description perl
perl components for the perl-Mail-Sendmail package.


%prep
%setup -q -n Mail-Sendmail-0.82
cd %{_builddir}/Mail-Sendmail-0.82

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Mail::Sendmail.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
